### ISSUE TITLE
Uncaught SyntaxError: Invalid regular expression: /^[(\d{4})-(\d{2})-(\d{2})] - ([\s\S] )(\.\w )$...

### ISSUE THREAD

**Issue by svnsbck** [zhuochun/md-writer#115]
Hi!

For some reason I'm getting this error, when trying to _publish a draft_ to my local Dropbox folder. Creating a _Draft_ or a _Post_ does work as it is supposed to. Publishing a _draft_ through results in this error. It used to work and I'm not sure where the error is.

Any help appreciated.

Cheers,

Sven

**Atom Version**: 1.4.1
**System**: Mac OS X 10.11.1
**Thrown From**: [markdown-writer](https://github.com/zhuochun/md-writer) package, v2.2.0

### Stack Trace

Uncaught SyntaxError: Invalid regular expression: /^[(\d{4})-(\d{2})-(\d{2})] - ([\s\S] )(\.\w )$/: Range out of order in character class

```
At /Users/blah/.atom/packages/markdown-writer/lib/utils.coffee:104

SyntaxError: Invalid regular expression: /^[(\d{4})-(\d{2})-(\d{2})] - ([\s\S] )(\.\w )$/: Range out of order in character class
    at new RegExp (native)
    at RegExp (native)
    at Object.untemplate (/Users/blah/.atom/packages/markdown-writer/lib/utils.coffee:104:33)
    at Object.parseFileSlug (/Users/blah/.atom/packages/markdown-writer/lib/helpers/template-helper.coffee:42:18)
    at PublishDraft.module.exports.PublishDraft.getSlug (/Users/blah/.atom/packages/markdown-writer/lib/commands/publish-draft.coffee:74:28)
    at Object.getFrontMatter (/Users/blah/.atom/packages/markdown-writer/lib/helpers/template-helper.coffee:31:21)
    at PublishDraft.module.exports.PublishDraft.getPostPath (/Users/blah/.atom/packages/markdown-writer/lib/commands/publish-draft.coffee:57:33)
    at PublishDraft.module.exports.PublishDraft.trigger (/Users/blah/.atom/packages/markdown-writer/lib/commands/publish-draft.coffee:22:18)
    at atom-text-editor.<anonymous> (/Users/blah/.atom/packages/markdown-writer/lib/markdown-writer.coffee:91:24)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
    at CommandPaletteView.module.exports.CommandPaletteView.confirmed (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/command-palette/lib/command-palette-view.js:183:32)
    at CommandPaletteView.module.exports.SelectListView.confirmSelection (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/lib/select-list-view.js:338:21)
    at space-pen-div.atom.commands.add.core:confirm (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/lib/select-list-view.js:109:19)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:536:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:359:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeydown (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:97:36)
    at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:3:61)
```

### Commands

```
     -0:54 markdown-writer:new-post (atom-text-editor.editor)
     -0:50 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:42.9.0 core:move-to-bottom (atom-text-editor.editor.is-focused)
     -0:42.6.0 markdown-writer:insert-new-line (atom-text-editor.editor.is-focused)
     -0:42.6.0 editor:newline (atom-text-editor.editor.is-focused)
     -0:42.4.0 markdown-writer:insert-new-line (atom-text-editor.editor.is-focused)
     -0:42.4.0 editor:newline (atom-text-editor.editor.is-focused)
  7x -0:38.7.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:28.8.0 markdown-writer:insert-new-line (atom-text-editor.editor.is-focused)
     -0:28.8.0 editor:newline (atom-text-editor.editor.is-focused)
     -0:28.6.0 markdown-writer:insert-new-line (atom-text-editor.editor.is-focused)
     -0:28.6.0 editor:newline (atom-text-editor.editor.is-focused)
     -0:27.5.0 core:save (atom-text-editor.editor.is-focused)
     -0:05.5.0 command-palette:toggle (atom-text-editor.editor.is-focused)
     -0:02.4.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:02.4.0 markdown-writer:publish-draft (atom-text-editor.editor)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "center-screen",
      "minimap"
    ],
    "themes": [
      "native-ui",
      "one-light-syntax"
    ]
  },
  "markdown-writer": {
    "fileExtension": ".md",
    "newPostFileName": "[{year}-{month}-{day}] - {title}{extension}",
    "siteDraftsDir": "[Drafts]",
    "siteLocalDir": "/Users/blah/Dropbox/[Writing]",
    "sitePostsDir": "[Posts]/[{year}]"
  }
}
```

### Installed Packages

```coffee
# User
file-icons, v1.6.14
markdown-mindmap, v0.2.4
markdown-table-formatter, v2.7.2
markdown-writer, v2.2.0
native-ui, v0.16.1
typewriter, v0.3.5
wordcount, v2.5.0

# Dev
No dev packages
```

**Comment by zhuochun** [comment]
Oops. It is caused by the `[` and `']` in `[{year}-{month}-{day}]`.

Will fix this in next release. Thanks for reporting.

**Comment by svnsbck** [comment]
Great! Glad I could help.
