### ISSUE TITLE
Syntax error on line 58, column 15: Unexpected Call

### ISSUE THREAD

**Issue by smallzzy** [zhuochun/md-writer#118]
steps to reproduce:

1. Add project config
2. add `urlForTags`
3. go to a post and manage tags
4. crashed.

Solve:
1. comment line 58 in the config
`siteLinkPath: path.join(atom.getConfigDirPath(), "#{@prefix}-links.cson")`
2. no more crashing

**Atom Version**: 1.4.3
**System**: Windows 10 Pro
**Thrown From**: [markdown-writer](https://github.com/zhuochun/md-writer) package, v2.3.0

### Stack Trace

Failed to activate the markdown-writer package

```
At Syntax error on line 58, column 15: Unexpected Call

SyntaxError: Syntax error on line 58, column 15: Unexpected Call
  at transformNode (C:\Users\small\AppData\Local\atom\app-1.4.3\resources\app.asar\node_modules\season\node_modules\cson-parser\lib\parse.js:195:13)
  at C:\Users\small\AppData\Local\atom\app-1.4.3\resources\app.asar\node_modules\season\node_modules\cson-parser\lib\parse.js:114:17
  at Array.reduce (native)
  at nodeTransforms.Obj (C:\Users\small\AppData\Local\atom\app-1.4.3\resources\app.asar\node_modules\season\node_modules\cson-parser\lib\parse.js:107:30)
  at transformNode (C:\Users\small\AppData\Local\atom\app-1.4.3\resources\app.asar\node_modules\season\node_modules\cson-parser\lib\parse.js:197:12)
  at nodeTransforms.Value (C:\Users\small\AppData\Local\atom\app-1.4.3\resources\app.asar\node_modules\season\node_modules\cson-parser\lib\parse.js:79:14)
  at transformNode (C:\Users\small\AppData\Local\atom\app-1.4.3\resources\app.asar\node_modules\season\node_modules\cson-parser\lib\parse.js:197:12)
  at nodeTransforms.Block (C:\Users\small\AppData\Local\atom\app-1.4.3\resources\app.asar\node_modules\season\node_modules\cson-parser\lib\parse.js:76:14)
  at transformNode (C:\Users\small\AppData\Local\atom\app-1.4.3\resources\app.asar\node_modules\season\node_modules\cson-parser\lib\parse.js:197:12)
  at Object.parse (C:\Users\small\AppData\Local\atom\app-1.4.3\resources\app.asar\node_modules\season\node_modules\cson-parser\lib\parse.js:203:12)
  at parseObject (C:\Users\small\AppData\Local\atom\app-1.4.3\resources\app.asar\node_modules\season\lib\cson.js:42:23)
  at parseContentsSync (C:\Users\small\AppData\Local\atom\app-1.4.3\resources\app.asar\node_modules\season\lib\cson.js:68:16)
  at Object.module.exports.readFileSync (C:\Users\small\AppData\Local\atom\app-1.4.3\resources\app.asar\node_modules\season\lib\cson.js:170:14)
  at Configuration._loadProjectConfig (C:\Users\small\.atom\packages\markdown-writer\lib\config.coffee:241:19)
  at Configuration.getProject (C:\Users\small\.atom\packages\markdown-writer\lib\config.coffee:227:15)
  at Configuration.getEngine (C:\Users\small\.atom\packages\markdown-writer\lib\config.coffee:207:15)
  at Configuration.getCurrentDefault (C:\Users\small\.atom\packages\markdown-writer\lib\config.coffee:216:6)
  at Object.<anonymous> (C:\Users\small\.atom\packages\markdown-writer\lib\config-basic.coffee:48:21)
  at Object.<anonymous> (C:\Users\small\.atom\packages\markdown-writer\lib\config-basic.coffee:1:1)
  at Module._compile (C:\Users\small\AppData\Local\atom\app-1.4.3\resources\app.asar\src\native-compile-cache.js:103:30)
  at Object.defineProperty.value [as .coffee] (C:\Users\small\AppData\Local\atom\app-1.4.3\resources\app.asar\src\compile-cache.js:208:21)
  at Module.load (module.js:355:32)
  at Function.Module._load (module.js:310:12)
  at Module.require (module.js:365:17)
  at require (C:\Users\small\AppData\Local\atom\app-1.4.3\resources\app.asar\src\native-compile-cache.js:50:27)
  at Object.<anonymous> (C:\Users\small\.atom\packages\markdown-writer\lib\markdown-writer.coffee:4:15)
  at Object.<anonymous> (C:\Users\small\.atom\packages\markdown-writer\lib\markdown-writer.coffee:1:1)
  at Module._compile (C:\Users\small\AppData\Local\atom\app-1.4.3\resources\app.asar\src\native-compile-cache.js:103:30)
  at Object.defineProperty.value [as .coffee] (C:\Users\small\AppData\Local\atom\app-1.4.3\resources\app.asar\src\compile-cache.js:208:21)
  at Module.load (module.js:355:32)
  at Function.Module._load (module.js:310:12)
  at Module.require (module.js:365:17)
  at require (C:\Users\small\AppData\Local\atom\app-1.4.3\resources\app.asar\src\native-compile-cache.js:50:27)
  at Package.module.exports.Package.requireMainModule (C:\Users\small\AppData\Local\atom\app-1.4.3\resources\app.asar\src\package.js:722:27)
  at Package.module.exports.Package.activateNow (C:\Users\small\AppData\Local\atom\app-1.4.3\resources\app.asar\src\package.js:173:16)
  at C:\Users\small\AppData\Local\atom\app-1.4.3\resources\app.asar\src\package.js:802:25
  at Function.module.exports.Emitter.simpleDispatch (C:\Users\small\AppData\Local\atom\app-1.4.3\resources\app.asar\node_modules\event-kit\lib\emitter.js:25:14)
  at Emitter.module.exports.Emitter.emit (C:\Users\small\AppData\Local\atom\app-1.4.3\resources\app.asar\node_modules\event-kit\lib\emitter.js:125:28)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (C:\Users\small\AppData\Local\atom\app-1.4.3\resources\app.asar\src\command-registry.js:241:20)
  at CommandRegistry.handleCommandEvent (C:\Users\small\AppData\Local\atom\app-1.4.3\resources\app.asar\src\command-registry.js:3:61)
  at CommandRegistry.module.exports.CommandRegistry.dispatch (C:\Users\small\AppData\Local\atom\app-1.4.3\resources\app.asar\src\command-registry.js:160:19)
  at AtomEnvironment.module.exports.AtomEnvironment.dispatchApplicationMenuCommand (C:\Users\small\AppData\Local\atom\app-1.4.3\resources\app.asar\src\atom-environment.js:1013:28)
  at emitOne (events.js:77:13)
  at EventEmitter.emit (events.js:169:7)

```

### Commands

```
  2x -0:09.3.0 markdown-writer:manage-post-tags (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
```

### Config

```json
{
  "core": {},
  "markdown-writer": {}
}
```

### Installed Packages

```coffee
# User
color-picker, v2.1.1
markdown-writer, v2.3.0
minimap, v4.19.0
pigments, v0.23.1

# Dev
No dev packages
```

**Comment by zhuochun** [comment]
Could you share your project configs? Thanks

**Comment by zhuochun** [comment]
Thanks will remove the line from config.
