### ISSUE TITLE
Enter is not possible

### ISSUE THREAD

**Issue by rubeonline** [zhuochun/md-writer#121]
When I start to edit and write something and press enter for a new line a exception is thrown.

**Atom Version**: 1.5.3
**System**: Mac OS X 10.11.1
**Thrown From**: [markdown-writer](https://github.com/zhuochun/md-writer) package, v2.3.0

### Stack Trace

Failed to activate the markdown-writer package

```
At Syntax error on line 58, column 15: Unexpected Call

SyntaxError: Syntax error on line 58, column 15: Unexpected Call
  at transformNode (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/season/node_modules/cson-parser/lib/parse.js:195:13)
  at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/season/node_modules/cson-parser/lib/parse.js:114:17
  at Array.reduce (native)
  at nodeTransforms.Obj (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/season/node_modules/cson-parser/lib/parse.js:107:30)
  at transformNode (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/season/node_modules/cson-parser/lib/parse.js:197:12)
  at nodeTransforms.Value (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/season/node_modules/cson-parser/lib/parse.js:79:14)
  at transformNode (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/season/node_modules/cson-parser/lib/parse.js:197:12)
  at nodeTransforms.Block (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/season/node_modules/cson-parser/lib/parse.js:76:14)
  at transformNode (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/season/node_modules/cson-parser/lib/parse.js:197:12)
  at Object.parse (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/season/node_modules/cson-parser/lib/parse.js:203:12)
  at parseObject (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/season/lib/cson.js:42:23)
  at parseContentsSync (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/season/lib/cson.js:68:16)
  at Object.module.exports.readFileSync (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/season/lib/cson.js:170:14)
  at Configuration._loadProjectConfig (/Users/Sergio/.atom/packages/markdown-writer/lib/config.coffee:241:19)
  at Configuration.getProject (/Users/Sergio/.atom/packages/markdown-writer/lib/config.coffee:227:15)
  at Configuration.getEngine (/Users/Sergio/.atom/packages/markdown-writer/lib/config.coffee:207:15)
  at Configuration.getCurrentDefault (/Users/Sergio/.atom/packages/markdown-writer/lib/config.coffee:216:6)
  at Object.<anonymous> (/Users/Sergio/.atom/packages/markdown-writer/lib/config-basic.coffee:48:21)
  at Object.<anonymous> (/Users/Sergio/.atom/packages/markdown-writer/lib/config-basic.coffee:1:1)
  at Module._compile (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
  at Object.defineProperty.value [as .coffee] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
  at Module.load (module.js:355:32)
  at Function.Module._load (module.js:310:12)
  at Module.require (module.js:365:17)
  at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
  at Object.<anonymous> (/Users/Sergio/.atom/packages/markdown-writer/lib/markdown-writer.coffee:4:15)
  at Object.<anonymous> (/Users/Sergio/.atom/packages/markdown-writer/lib/markdown-writer.coffee:1:1)
  at Module._compile (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
  at Object.defineProperty.value [as .coffee] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
  at Module.load (module.js:355:32)
  at Function.Module._load (module.js:310:12)
  at Module.require (module.js:365:17)
  at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
  at Package.module.exports.Package.requireMainModule (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:720:27)
  at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:172:16)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:800:25
  at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:241:20)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:536:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:359:22)
  at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeydown (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:97:36)
  at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:3:61)

```

### Commands

```
     -0:00.7.0 markdown-writer:insert-new-line (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "spell-check"
    ],
    "themes": [
      "one-light-ui",
      "one-light-syntax"
    ]
  },
  "markdown-writer": {}
}
```

### Installed Packages

```coffee
# User
markdown-writer, v2.3.0

# Dev
No dev packages
```

**Comment by zhuochun** [comment]
Hi, if you have created a project config `_mdwriter.cson`, please remove the line `siteLinkPath: path.join(atom.getConfigDirPath(), "#{@prefix}-links.cson")`.

**Comment by rubeonline** [comment]
Thank you. Works like a charm.

**Comment by zhuochun** [comment]
Great :+1:
