### ISSUE TITLE
Uncaught TypeError: Cannot read property 'grammars' of null

### ISSUE THREAD

**Issue by Wcc723** [zhuochun/md-writer#131]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.6.2
**System**: Mac OS X 10.11.4
**Thrown From**: [markdown-writer](https://github.com/zhuochun/md-writer) package, v2.3.2

### Stack Trace

Uncaught TypeError: Cannot read property 'grammars' of null

```
At /Users/oushimakoto/.atom/packages/markdown-writer/lib/config.coffee:123

TypeError: Cannot read property 'grammars' of null
    at Object.module.exports._valueForKeyPath (/Users/oushimakoto/.atom/packages/markdown-writer/lib/config.coffee:123:23)
    at Object.module.exports.getProject (/Users/oushimakoto/.atom/packages/markdown-writer/lib/config.coffee:101:6)
    at Object.module.exports.get (/Users/oushimakoto/.atom/packages/markdown-writer/lib/config.coffee:66:13)
    at Object.module.exports.isMarkdown (/Users/oushimakoto/.atom/packages/markdown-writer/lib/markdown-writer.coffee:99:19)
    at atom-text-editor.<anonymous> (/Users/oushimakoto/.atom/packages/markdown-writer/lib/markdown-writer.coffee:89:38)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:580:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:388:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeydown (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:97:36)
    at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:3:61)
```

### Commands

```
     -1:51.4.0 pane:show-item-1 (div.package-detail.panels-item)
     -1:50.9.0 symbols-view:toggle-file-symbols (atom-text-editor.editor.is-focused)
     -1:50 editor:consolidate-selections (atom-text-editor.editor.mini.is-focused)
     -1:50 core:cancel (atom-text-editor.editor.mini.is-focused)
     -1:47.4.0 pane:show-item-2 (atom-text-editor.editor.is-focused)
     -1:44.9.0 pane:show-item-1 (button.btn.icon.enablement.icon-playback-pause)
     -1:44.6.0 symbols-view:toggle-file-symbols (atom-text-editor.editor.is-focused)
     -1:43.8.0 editor:consolidate-selections (atom-text-editor.editor.mini.is-focused)
     -1:43.8.0 core:cancel (atom-text-editor.editor.mini.is-focused)
     -1:42.6.0 markdown-writer:insert-new-line (atom-text-editor.editor.is-focused)
  2x -1:33.7.0 core:copy (atom-notification.fatal.icon.icon-bug.native-key-bindings.has-detail.has-close.has-stack)
  3x -0:53.6.0 markdown-writer:toggle-italic-text (atom-text-editor.editor.is-focused)
     -0:43.1.0 core:copy (atom-notification.fatal.icon.icon-bug.native-key-bindings.has-detail.has-close.has-stack)
     -0:09.3.0 pane:show-item-2 (atom-notification.fatal.icon.icon-bug.native-key-bindings.has-detail.has-close.has-stack)
     -0:02.9.0 pane:show-item-1 (button.btn.icon.enablement.icon-playback-pause)
     -0:01.4.0 markdown-writer:insert-new-line (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "audioBeep": false,
    "closeEmptyWindows": false,
    "destroyEmptyPanes": false,
    "disabledPackages": [
      "markdown-preview"
    ],
    "ignoredNames": [
      ".git",
      ".svn",
      ".DS_Store"
    ],
    "projectHome": "/user/github"
  },
  "markdown-writer": {
    "fileExtension": ".md",
    "grammars": "",
    "siteEngine": "jekyll",
    "sitePostsDir": "/Users/oushimakoto/github/wcc723.github.io"
  }
}
```

### Installed Packages

```coffee
# User
angularjs, v0.3.0
emmet, v2.4.3
javascript-snippets, v1.0.0
language-coffee-script-angular, v2.2.0
markdown-writer, v2.3.2
ruby-slim, v0.2.0
sync-settings, v0.7.2
terminal-panel, v1.14.1

# Dev
No dev packages
```

**Comment by zhuochun** [comment]
Do you have a project specific config?

**Comment by Wcc723** [comment]
I didn't have project config. Is it necessary?

This is my Jekyll project (personal blog).
https://github.com/Wcc723/wcc723.github.io

**Comment by zhuochun** [comment]
Weird, the error backtrace shows it was loading a project specific config.

Can you try restart Atom. and modify `"grammars": "",` to `"grammars": []`? By the way, if you set `"grammars": []`, all the hotkeys will not triggered.

**Comment by Wcc723** [comment]
Hi, when I add `siteEngine: "jekyll"` to `_mdwriter.cson` line 2 this problem was resolve. 

_mdwriter.cson
```
# +# static engine of your blog
siteEngine: "jekyll"
# +# root directory of your blog
```
