### ISSUE TITLE
Uncaught TypeError: Cannot read property 'categories' of null

### ISSUE THREAD

**Issue by liammagee** [zhuochun/md-writer#137]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.7.4
**System**: Mac OS X 10.11.5
**Thrown From**: [markdown-writer](https://github.com/zhuochun/md-writer) package, v2.3.3

### Stack Trace

Uncaught TypeError: Cannot read property 'categories' of null

```
At /Users/liam/.atom/packages/markdown-writer/lib/helpers/front-matter.coffee:44

TypeError: Cannot read property 'categories' of null
    at FrontMatter.module.exports.FrontMatter.normalizeField (/Users/liam/.atom/packages/markdown-writer/lib/helpers/front-matter.coffee:44:18)
    at FrontMatter.module.exports.FrontMatter.getArray (/Users/liam/.atom/packages/markdown-writer/lib/helpers/front-matter.coffee:56:6)
    at Object.getEditor (/Users/liam/.atom/packages/markdown-writer/lib/helpers/template-helper.coffee:55:34)
    at InsertImageView.module.exports.InsertImageView.display (/Users/liam/.atom/packages/markdown-writer/lib/views/insert-image-view.coffee:68:35)
    at atom-text-editor.<anonymous> (/Users/liam/.atom/packages/markdown-writer/lib/markdown-writer.coffee:83:24)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Users/liam/Downloads/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at /Users/liam/Downloads/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Users/liam/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:580:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Users/liam/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:388:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/Users/liam/Downloads/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:98:36)
    at HTMLDocument.<anonymous> (/Users/liam/Downloads/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:3:61)
```

### Commands

```
     -2:16 core:move-right (atom-text-editor.editor.power-mode.is-focused)
     -2:15.4.0 editor:move-to-beginning-of-word (atom-text-editor.editor.power-mode.is-focused)
     -2:14.6.0 core:select-right (atom-text-editor.editor.power-mode.is-focused)
     -2:13.8.0 core:move-right (atom-text-editor.editor.power-mode.is-focused)
     -2:13.3.0 editor:select-to-end-of-word (atom-text-editor.editor.power-mode.is-focused)
  3x -2:11.9.0 core:backspace (atom-text-editor.editor.power-mode.is-focused)
     -2:07.7.0 markdown-writer:insert-new-line (atom-text-editor.editor.power-mode.is-focused)
     -2:07.1.0 markdown-writer:indent-list-line (atom-text-editor.editor.power-mode.is-focused)
  3x -2:04.9.0 core:backspace (atom-text-editor.editor.power-mode.is-focused)
     -2:00.9.0 editor:select-to-beginning-of-word (atom-text-editor.editor.power-mode.is-focused)
     -1:59.6.0 editor:move-to-end-of-screen-line (atom-text-editor.editor.power-mode.is-focused)
  2x -0:16.3.0 core:move-down (atom-text-editor.editor.power-mode.is-focused)
     -0:15.6.0 markdown-writer:insert-new-line (atom-text-editor.editor.power-mode.is-focused)
     -0:15.6.0 docblockr:parse-enter (atom-text-editor.editor.power-mode.is-focused)
     -0:15.6.0 editor:newline (atom-text-editor.editor.power-mode.is-focused)
     -0:02.7.0 markdown-writer:insert-image (atom-text-editor.editor.power-mode.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "language-gfm",
      "linter-lintr",
      "language-babel",
      "linter-js-standard",
      "atom-autocomplete-php"
    ],
    "themes": [
      "atom-dark-ui",
      "atom-dark-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
activate-power-mode, v0.5.2
aligner-php, v1.0.0
atom-beautify, v0.29.7
atom-ternjs, v0.14.1
autoclose-html, v0.23.0
autocomplete-solidity, v0.1.0
change-case, v0.6.0
color-picker, v2.1.1
docblockr, v0.7.3
emmet, v2.4.3
highlight-line, v0.11.1
highlight-selected, v0.11.2
jshint, v1.8.5
language-ethereum, v0.3.8
language-glsl, v2.0.1
language-markdown, v0.13.0
language-r, v0.4.1
linter, v1.11.4
linter-csslint, v1.3.2
linter-eslint, v7.2.2
linter-htmlhint, v1.1.4
linter-js-yaml, v1.2.5
linter-jshint, v2.1.0
linter-php, v1.2.0
linter-phpcs, v1.4.0
linter-phpmd, v1.4.1
linter-scss-lint, v3.0.4
linter-tidy, v2.1.0
markdown-scroll-sync, v2.1.2
markdown-writer, v2.3.3
merge-conflicts, v1.4.3
minimap, v4.23.5
minimap-git-diff, v4.3.1
navigate, v0.1.15
pigments, v0.26.3
project-manager, v2.9.7
wordcount, v2.6.0
wordpress-api, v1.2.2

# Dev
No dev packages
```

**Comment by zhuochun** [comment]
I cannot re-produce this. Please provide more details if possible.

**Comment by zhuochun** [comment]
Closed because cannot re-produce. Feel free to attach steps and re-open this issue. Thanks.
