### ISSUE TITLE
Uncaught ReferenceError: sampleConfigFile is not defined

### ISSUE THREAD

**Issue by wreichard** [zhuochun/md-writer#168]
[Enter steps to reproduce below:]

1. Install package
2. Attempt to define project configs

**Atom Version**: 1.8.0
**System**: Ubuntu 16.04
**Thrown From**: [markdown-writer](https://github.com/zhuochun/md-writer) package, v2.5.0

### Stack Trace

Uncaught ReferenceError: sampleConfigFile is not defined

```
At /home/wreichard/.atom/packages/markdown-writer/lib/config.coffee:125

ReferenceError: sampleConfigFile is not defined
    at Object.module.exports.getSampleConfigFile (/home/wreichard/.atom/packages/markdown-writer/lib/config.coffee:125:27)
    at CreateProjectConfigs.module.exports.CreateProjectConfigs.trigger (/home/wreichard/.atom/packages/markdown-writer/lib/commands/create-project-configs.coffee:13:38)
    at atom-workspace.<anonymous> (/home/wreichard/.atom/packages/markdown-writer/lib/markdown-writer.coffee:92:24)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app.asar/src/command-registry.js:260:29)
    at CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app.asar/src/command-registry.js:3:61)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (/usr/share/atom/resources/app.asar/src/command-registry.js:160:19)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchApplicationMenuCommand (/usr/share/atom/resources/app.asar/src/atom-environment.js:1100:28)
    at EventEmitter.outerCallback (/usr/share/atom/resources/app.asar/src/application-delegate.js:327:25)
    at emitTwo (events.js:87:13)
    at EventEmitter.emit (events.js:172:7)
```

### Commands

```
     -5:54.3.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -5:43.3.0 markdown-writer:create-project-configs (atom-text-editor.editor.is-focused)
     -4:51.8.0 settings-view:open (atom-text-editor.editor.is-focused)
     -3:22.5.0 editor:delete-to-beginning-of-word (atom-text-editor.editor.mini.is-focused)
  2x -3:19.4.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -1:43.3.0 pane:show-next-recently-used-item (atom-workspace.workspace.scrollbars-visible-always.theme-atom-light-syntax.theme-one-light-ui)
     -1:42.9.0 pane:move-active-item-to-top-of-stack (atom-workspace.workspace.scrollbars-visible-always.theme-atom-light-syntax.theme-one-light-ui)
     -1:39.1.0 application:new-file (ul.list-inline.tab-bar.inset-panel)
     -1:30 markdown-writer:new-draft (atom-text-editor.editor.is-focused)
     -1:26.7.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -1:26.3.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -1:13.5.0 markdown-writer:create-project-configs (atom-text-editor.editor.is-focused)
     -1:05.0 editor:consolidate-selections (atom-text-editor.editor.is-focused)
     -1:05.0 core:cancel (atom-text-editor.editor.is-focused)
     -0:41.5.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -0:01.6.0 markdown-writer:create-project-configs (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "one-light-ui",
      "atom-light-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
build-coffee, v0.5.2
coffee-navigator, v0.0.18
markdown-writer, v2.5.0
pp-markdown, v0.0.2
tool-bar-markdown-writer, v0.2.0

# Dev
No dev packages
```

**Comment by zhuochun** [comment]
Probably need to restart/reload Atom after package install, then try again.

**Comment by wreichard** [comment]
Tried that and it's still there. Some kind of dependency I'm missing, maybe?

**Comment by zhuochun** [comment]
Ah found the bug. thanks for catching it. Will fix it soon. 

You can copy the content [here](https://github.com/zhuochun/md-writer/blob/master/lib/config.cson) for project specific configs.
