### ISSUE TITLE
Uncaught TypeError: Path must be a string. Received undefined

### ISSUE THREAD

**Issue by guzishiwo** [zhuochun/md-writer#171]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.9.8
**System**: Ubuntu 16.04.1
**Thrown From**: [markdown-writer](https://github.com/zhuochun/md-writer) package, v2.5.1
### Stack Trace

Uncaught TypeError: Path must be a string. Received undefined

```
At path.js:7

TypeError: Path must be a string. Received undefined
    at assertPath (path.js:7:11)
    at join (path.js:1253:7)
    at Object.getPackagePath (/home/wei/.atom/packages/md-writer/lib/utils.coffee:91:13)
    at CreateDefaultKeymaps.module.exports.CreateDefaultKeymaps.sampleKeymapFile (/home/wei/.atom/packages/md-writer/lib/commands/create-default-keymaps.coffee:19:11)
    at CreateDefaultKeymaps.module.exports.CreateDefaultKeymaps.trigger (/home/wei/.atom/packages/md-writer/lib/commands/create-default-keymaps.coffee:9:32)
    at atom-workspace.<anonymous> (/home/wei/.atom/packages/md-writer/lib/markdown-writer.coffee:92:24)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app.asar/src/command-registry.js:260:29)
    at CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app.asar/src/command-registry.js:3:61)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (/usr/share/atom/resources/app.asar/src/command-registry.js:160:19)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchApplicationMenuCommand (/usr/share/atom/resources/app.asar/src/atom-environment.js:1104:28)
    at EventEmitter.outerCallback (/usr/share/atom/resources/app.asar/src/application-delegate.js:329:25)
    at emitTwo (events.js:100:13)
    at EventEmitter.emit (events.js:185:7)
```
### Commands

```
     -1:10.6.0 markdown-pdf:convert (div.markdown-preview.native-key-bindings)
     -0:57.2.0 markdown-writer:publish-draft (div.markdown-preview.native-key-bindings)
     -0:48.9.0 markdown-writer:insert-image (div.markdown-preview.native-key-bindings)
     -0:41 markdown-writer:toggle-codeblock-text (atom-text-editor.editor.vim-mode-plus.normal-mode.is-focused)
     -0:36.1.0 vim-mode-plus:reset-normal-mode (atom-text-editor.editor.vim-mode-plus.normal-mode.is-focused)
     -0:35.9.0 vim-mode-plus:move-up (atom-text-editor.editor.vim-mode-plus.is-focused.normal-mode)
  6x -0:35.3.0 vim-mode-plus:delete (atom-text-editor.editor.vim-mode-plus.is-focused.normal-mode)
     -0:33.3.0 vim-mode-plus:insert-below-with-newline (atom-text-editor.editor.vim-mode-plus.is-focused.normal-mode)
     -0:26.2.0 markdown-writer:manage-post-tags (atom-text-editor.editor.vim-mode-plus.insert-mode.is-focused)
     -0:14.2.0 vim-mode-plus:activate-normal-mode (atom-text-editor.editor.vim-mode-plus.insert-mode.is-focused)
     -0:13.8.0 vim-mode-plus:reset-normal-mode (atom-text-editor.editor.vim-mode-plus.is-focused.normal-mode)
     -0:13.4.0 core:cancel (atom-text-editor.editor.mini.is-focused)
     -0:00.1.0 markdown-writer:create-default-keymaps (atom-text-editor.editor.vim-mode-plus.normal-mode.is-focused)
```
### Config

``` json
{}
```
### Installed Packages

``` coffee
# User
script, v3.8.3 (inactive)
tidy-markdown, v3.0.1 (active)
vim-mode-plus, v0.50.0 (active)
autocomplete-python, v1.8.6 (active)
markdown-pdf, v1.5.0 (active)
markdown-scroll-sync, v2.1.2 (active)
markdown-writer, v2.5.1 (active)
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.51.0 (inactive)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.43.0 (inactive)
base16-tomorrow-dark-theme, v1.1.0 (inactive)
base16-tomorrow-light-theme, v1.1.1 (inactive)
one-dark-ui, v1.3.2 (active)
one-light-ui, v1.3.2 (inactive)
one-dark-syntax, v1.2.0 (active)
one-light-syntax, v1.2.0 (inactive)
solarized-dark-syntax, v1.0.2 (inactive)
solarized-light-syntax, v1.0.2 (inactive)
about, v1.5.2 (active)
archive-view, v0.61.1 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.11.1 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.31.0 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (active)
background-tips, v0.26.0 (active)
bookmarks, v0.41.0 (active)
bracket-matcher, v0.82.1 (active)
command-palette, v0.38.0 (inactive)
deprecation-cop, v0.54.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.39.0 (active)
fuzzy-finder, v1.3.0 (active)
git-diff, v1.1.0 (active)
find-and-replace, v0.198.0 (inactive)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.1 (active)
image-view, v0.58.0 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.0 (active)
link, v0.31.1 (inactive)
markdown-preview, v0.158.0 (active)
metrics, v0.53.1 (active)
notifications, v0.64.1 (active)
open-on-github, v1.2.0 (inactive)
package-generator, v1.0.0 (inactive)
settings-view, v0.238.2 (active)
snippets, v1.0.2 (active)
spell-check, v0.67.1 (active)
status-bar, v1.4.1 (active)
styleguide, v0.46.0 (active)
symbols-view, v0.113.0 (inactive)
tabs, v0.98.1 (active)
timecop, v0.33.1 (active)
tree-view, v0.208.0 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.34.0 (active)
whitespace, v0.32.2 (active)
wrap-guide, v0.38.1 (active)
language-c, v0.52.1 (active)
language-clojure, v0.21.0 (active)
language-coffee-script, v0.47.0 (active)
language-csharp, v0.12.1 (active)
language-css, v0.36.2 (active)
language-gfm, v0.86.0 (active)
language-git, v0.13.0 (active)
language-go, v0.42.0 (active)
language-html, v0.44.1 (active)
language-hyperlink, v0.16.0 (active)
language-java, v0.22.0 (active)
language-javascript, v0.119.0 (active)
language-json, v0.18.0 (active)
language-less, v0.29.3 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.35.0 (active)
language-php, v0.37.0 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.0 (active)
language-ruby, v0.68.5 (active)
language-ruby-on-rails, v0.25.0 (active)
language-sass, v0.52.0 (active)
language-shellscript, v0.22.3 (active)
language-source, v0.9.0 (active)
language-sql, v0.21.1 (active)
language-text, v0.7.1 (active)
language-todo, v0.28.0 (active)
language-toml, v0.18.0 (active)
language-xml, v0.34.8 (active)
language-yaml, v0.26.0 (active)

# Dev
No dev packages
```

**Comment by zhuochun** [comment]
Is it happened immediately after installation? Might try again after atom restarted.

**Comment by zhuochun** [comment]
Any updates? Feel free to re-open the ticket.

**Comment by wutaotao2015** [comment]
trying to create defaults keymap,this error is reported

**Comment by zhuochun** [comment]
@wutaotao2015 plz restart Atom and try again?

**Comment by wutaotao2015** [comment]
I'm sorry, it didn't work,I attached the problem report image here.
Hope it can help.
![2017-04-16 9 14 55](https://cloud.githubusercontent.com/assets/11647617/25071455/5e60b496-22ea-11e7-9573-b2925bb0cfa7.png)

**Comment by zhuochun** [comment]
@wutaotao2015 sorry miss your comment.

Can open Atom `Dev Tools` , and execute the following commands and let me know the results?

```
atom.getConfigDirPath()

atom.packages.resolvePackagePath("markdown-writer")

process.platform
```
