### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, open '$ATOM_HOME/packages\atom-terminal-panel\...

### ISSUE THREAD

**Issue by liuboteach** [zhuochun/md-writer#227]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.22.1 x64
**Electron**: 1.6.15
**OS**: Unknown Windows version
**Thrown From**: [markdown-writer](https://github.com/zhuochun/md-writer) package 2.7.3

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, open 'C:\Users\10284\.atom\packages\atom-terminal-panel\lib\atp-view.coffee'

```
At fs.js:558

Error: ENOENT: no such file or directory, open 'C:\Users\10284\.atom\packages\atom-terminal-panel\lib\atp-view.coffee'
  at Object.fs.openSync (fs.js:558:18)
  at Object.module.(anonymous function) [as openSync] (ELECTRON_ASAR.js:173:20)
  at Object.fs.readFileSync (fs.js:468:33)
  at Object.fs.readFileSync (ELECTRON_ASAR.js:506:29)
  at Object.exports._compileFile (/packages/markdown-writer/node_modules/coffee-script/lib/coffee-script/coffee-script.js:221:14)
  at getSourceMap (/packages/markdown-writer/node_modules/coffee-script/lib/coffee-script/coffee-script.js:329:22)
  at getSourceMapping (/packages/markdown-writer/node_modules/coffee-script/lib/coffee-script/coffee-script.js:337:19)

```

### Commands

```
     -4:38.1.0 platformio-ide-terminal:new (input.hidden-input)
     -2:19.5.0 intentions:highlight (input.hidden-input)
     -2:19.4.0 tree-view:toggle (input.hidden-input)
     -0:14.8.0 markdown-writer:insert-new-line (input.hidden-input)
     -0:14.8.0 editor:newline (input.hidden-input)
```

### Non-Core Packages

```
advanced-open-file 0.16.7 
ask-stack 2.2.0 
atom-beautify 0.30.9 
atom-clock 0.1.15 
atom-material-syntax 1.0.7 
atom-material-syntax-light 0.4.6 
atom-material-ui 2.0.6 
atom-ternjs 0.18.3 
autocomplete-paths 2.12.1 
browser-plus 0.0.98 
busy-signal 1.4.3 
color-picker 2.2.5 
emmet 2.4.3 
es6-javascript 1.0.0 
file-icons 2.1.14 
git-plus 7.10.0 
intentions 1.1.5 
language-babel 2.79.0 
linter 2.2.0 
linter-jscs 4.1.3 
linter-jshint 3.1.6 
linter-markdown 5.2.0 
linter-ui-default 1.6.10 
markdown-writer 2.7.3 
minimap 4.29.7 
open-in-browsers 0.0.30 
pigments 0.40.2 
platformio-ide-terminal 2.7.0 
react-snippets 1.0.1 
script 3.17.3 
sync-settings 0.8.3 
```

**Comment by zhuochun** [comment]
Please provide reproducing steps to help locate this error.
