### ISSUE TITLE
Math support

### ISSUE THREAD

**Issue by mett96** [zhuochun/md-writer#254]
Hi, there is a way to introduce a snippet as the code snippet. 
for instance I write math and press enter and automatically it is introduces 
$$
\n 
$$

thank you

**Comment by mett96** [comment]
thank you

**Comment by mett96** [comment]
I downloaded this new version updated. But now when I open Atom it is showed this error 

[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.31.2 x64
**Electron**: 2.0.7
**OS**: Mac OS X 10.14
**Thrown From**: 'md-writer' package vundefined


### Stack Trace

Uncaught Error: Cannot find module 'season'

```
At module.js:545

Error: Cannot find module 'season'
    at Module._resolveFilename (module.js:543:15)
    at Module._resolveFilename (/Applications/Atom.app/Contents/Resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.get_Module._resolveFilename (/Applications/Atom.app/Contents/Resources/app/src/module-cache.js:354:58)
    at Module.require (/app.asar/static/index.js:40:43)
    at require (/Applications/Atom.app/Contents/Resources/app/src/native-compile-cache.js:66:33)
    at /packages/md-writer/lib/config.coffee:5:10)
    at /packages/md-writer/lib/config.coffee:177:4)
    at /packages/md-writer/lib/config.coffee:181:3)
    at Module.get_Module._compile (/Applications/Atom.app/Contents/Resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .coffee] (/Applications/Atom.app/Contents/Resources/app/src/compile-cache.js:240:29)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (/Applications/Atom.app/Contents/Resources/app/src/native-compile-cache.js:66:33)
    at /packages/md-writer/lib/markdown-writer.coffee:6:12)
    at /packages/md-writer/lib/markdown-writer.coffee:175:4)
    at /packages/md-writer/lib/markdown-writer.coffee:179:3)
    at Module.get_Module._compile (/Applications/Atom.app/Contents/Resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .coffee] (/Applications/Atom.app/Contents/Resources/app/src/compile-cache.js:240:29)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (internal/module.js:11:18)
    at customRequire (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:96:26)
    at Package.requireMainModule (/Applications/Atom.app/Contents/Resources/app/src/package.js:782:33)
    at Package.activateConfig (/Applications/Atom.app/Contents/Resources/app/src/package.js:267:16)
    at PackageManager.module.exports.PackageManager.packageHasSettings (/Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/package-manager.js:68:20)
    at PackageCard.hasSettings (/Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/package-card.js:794:40)
```

### Commands

```
```

### Non-Core Packages

```
atom-ide-ui 0.13.0 
atom-java-snippets 0.5.1 
character-table 0.4.3 
file-icons 2.1.25 
go-debug 1.6.2 
html-to-css 0.2.2 
ide-html 0.4.2 
ide-java 0.8.3 
language-arduino 0.4.3 
language-latex 1.2.0 
language-markdown 0.27.0 
language-matlab 0.2.1 
language-pfm 0.82.0 
latex-autocomplete 1.1.1 
latexer 0.3.0 
markdown-pdf 2.2.0 
markdown-preview-plus 3.7.0 
markdown-scroll-sync 2.1.2 
markdown-writer 2.9.0 
open-in-browser 0.5.2 
pandoc-convert 1.1.1 
pdf-view 0.71.0 
python-tools 0.6.9 
script 3.18.1 
teletype 0.13.3 
```

and the new features (math code) doesn't work

**Comment by mett96** [comment]
Ok sorry I made a mistake during the installation. But now if I go through the menu math work perfectly, but there isn't the snippet such as there is for code bold and so on
