### ISSUE TITLE
Manage Tags throw error

### ISSUE THREAD

**Issue by azu** [zhuochun/md-writer#27]
Hi, It seems that md-writer couldn't handle the tag like `C++`.

Steps to reproduce:

1. Click Package -> Markdown Writer -> Front Matter -> Manage Tags
2. Throw Error : `Uncaught SyntaxError: Invalid regular expression: /C++/: Nothing to repeat`

![2015-02-08 at 12 18](https://cloud.githubusercontent.com/assets/19714/6095054/a7acf980-af8c-11e4-86f1-3c0d7b564f6f.png)

**Atom Version**: 0.177.0
**System**: Mac OS X 10.10.2
**Thrown From**: [markdown-writer](https://github.com/zhuochun/md-writer) package, v0.10.0

### Stack Trace

Uncaught SyntaxError: Invalid regular expression: /C++/: Nothing to repeat

```
At /Users/azu/.atom/packages/markdown-writer/lib/manage-post-tags-view.coffee:78

SyntaxError: Invalid regular expression: /C++/: Nothing to repeat
  at new RegExp (native)
  at /Users/azu/.atom/packages/markdown-writer/lib/manage-post-tags-view.coffee:78:22
  at Array.forEach (native)
  at ManagePostTagsView.module.exports.ManagePostTagsView.rankTags (/Users/azu/.atom/packages/markdown-writer/lib/manage-post-tags-view.coffee:77:10)
  at /Users/azu/.atom/packages/markdown-writer/lib/manage-post-tags-view.coffee:69:8
  at Request._callback (/Users/azu/.atom/packages/markdown-writer/lib/utils.coffee:10:7)
  at Request.self.callback (/Applications/Atom.app/Contents/Resources/app/node_modules/less-cache/node_modules/less/node_modules/request/request.js:123:22)
  at Request.emit (events.js:119:17)
  at Request.<anonymous> (/Applications/Atom.app/Contents/Resources/app/node_modules/less-cache/node_modules/less/node_modules/request/request.js:1047:14)
  at Request.emit (events.js:138:20)
  at Gunzip.<anonymous> (/Applications/Atom.app/Contents/Resources/app/node_modules/less-cache/node_modules/less/node_modules/request/request.js:998:12)
  at Gunzip.emit (events.js:138:20)
  at _stream_readable.js:909:16
  at process._tickCallback (node.js:364:11)

```

### Commands

```
     -0:51.6 core:select-all (atom-text-editor.editor.mini)
     -0:50.6 core:confirm (atom-text-editor.editor.mini)
     -0:50.6 markdown-preview:toggle (atom-text-editor.editor)
     -0:47.0 command-palette:toggle (div.markdown-preview.native-key-bindings)
     -0:44.9 core:move-down (atom-text-editor.editor.mini)
     -0:44.7 core:confirm (atom-text-editor.editor.mini)
     -0:44.6 scroll-sync:toggle (div.markdown-preview.native-key-bindings)
     -0:42.5 command-palette:toggle (div.markdown-preview.native-key-bindings)
     -0:40.5 core:confirm (atom-text-editor.editor.mini)
     -0:40.5 scroll-sync:toggle (div.markdown-preview.native-key-bindings)
  2x -0:09.6 core:close (div.markdown-preview.native-key-bindings)
     -0:05.9 command-palette:toggle (atom-text-editor.editor)
     -0:03.5 core:select-all (atom-text-editor.editor.mini)
     -0:01.5 core:move-down (atom-text-editor.editor.mini)
     -0:01.2 core:confirm (atom-text-editor.editor.mini)
     -0:01.2 markdown-writer:manage-post-tags (atom-text-editor.editor)
```

### Config

```json
{
  "core": {
    "ignoredNames": [
      ".git",
      ".svn",
      ".DS_Store"
    ],
    "excludeVcsIgnoredPaths": false,
    "disabledPackages": [
      "markdown-helpers",
      "markdown-stream",
      "markdown-format",
      "jekyll-new-post"
    ],
    "themes": [
      "atom-mac-theme",
      "Writer"
    ]
  },
  "markdown-writer": {
    "fileExtension": ".md",
    "siteLocalDir": "/Users/azu/.ghq/github.com/efcl/efcl.github.io/",
    "urlForCategories": "http://efcl.info/assets/categories.json",
    "urlForPosts": "http://efcl.info/assets/posts.json",
    "urlForTags": "http://efcl.info/assets/tags.json",
    "sitePostsDir": "/Users/azu/.ghq/github.com/efcl/efcl.github.io/_post/{year}",
    "siteUrl": "http://efcl.info/",
    "siteEngine": "jekyll"
  }
}
```

### Installed Packages

```coffee
# User
Writer, v0.1.0
asciidoc-preview, v0.4.2
atom-mac-theme, v0.4.2
autocomplete-emojis, v1.0.0
autocomplete-paths, v1.0.2
file-icons, v1.4.8
git-plus, v4.4.1
github-issues, v0.3.0
japanese-wrap, v0.2.3
language-asciidoc, v0.11.1
linter-shellcheck, v0.0.6
markdown-writer, v0.10.0
preview-plus, v1.1.16
recent-files, v0.3.0
scroll-sync, v0.1.0

# Dev
No dev packages
```

**Comment by azu** [comment]
I thnink it needs to [escape RegExp special characters](https://github.com/sindresorhus/escape-string-regexp "Escape RegExp special characters") or handle the tag as a string.

**Comment by zhuochun** [comment]
Thanks. I forgot to escape special characters. I will fix this shortly.
