### ISSUE TITLE
The WebView must be attached to the DOM and the dom-ready event emitted before this method can be called.

### ISSUE THREAD

**Issue by haaase** [zhuochun/md-writer#291]
**Describe the bug**

When trying to edit a markdown document in atom, I get the following error: 

Failed to activate the markdown-writer package

```
At The WebView must be attached to the DOM and the dom-ready event emitted before this method can be called.

Error: The WebView must be attached to the DOM and the dom-ready event emitted before this method can be called.
    at getGuestInstanceId (/usr/lib/electron4/resources/electron.asar/renderer/web-view/web-view.js:241:13)
    at HTMLElement.send (/usr/lib/electron4/resources/electron.asar/renderer/web-view/web-view.js:272:77)
    at WebviewHandler.updateStyles (/packages/markdown-preview-plus/lib/markdown-preview-view/webview-handler.js:169:23)
    at WebviewHandler.disposables.add.atom.styles.onDidAddStyleElement (/packages/markdown-preview-plus/lib/markdown-preview-view/webview-handler.js:66:18)
    at Function.simpleDispatch (/usr/lib/atom/node_modules/event-kit/dist/emitter.js:64:14)
    at Emitter.emit (/usr/lib/atom/node_modules/event-kit/dist/emitter.js:257:28)
    at StyleManager.addStyleElement (/usr/lib/atom/src/style-manager.js:175:18)
    at StyleManager.addStyleSheet (/usr/lib/atom/src/style-manager.js:154:12)
    at Package.activateStylesheets (/usr/lib/atom/src/package.js:282:27)
    at Package.activateNow (/usr/lib/atom/src/package.js:217:12)
    at activationCommandSubscriptions.add.commandRegistry.onWillDispatch.event (/usr/lib/atom/src/package.js:859:22)
    at Function.simpleDispatch (/usr/lib/atom/node_modules/event-kit/dist/emitter.js:64:14)
    at Emitter.emit (/usr/lib/atom/node_modules/event-kit/dist/emitter.js:257:28)
    at CommandRegistry.handleCommandEvent (/usr/lib/atom/src/command-registry.js:360:18)
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/usr/lib/atom/node_modules/atom-keymap/lib/keymap-manager.js:617:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/usr/lib/atom/node_modules/atom-keymap/lib/keymap-manager.js:408:22)
    at WindowEventHandler.handleDocumentKeyEvent (/usr/lib/atom/src/window-event-handler.js:110:34)
```

**Atom**: 1.38.2 x64
**Electron**: 4.2.8
**OS**: linux 5.2.1-arch1-1-ARCH
**Thrown From**: [markdown-writer](https://github.com/zhuochun/md-writer) package 2.11.6

**To Reproduce**
1. Open markdown document in atom
2. Enter any character
3. See error

**Comment by zhuochun** [comment]
Can you disable `markdown-preview-plus` package and try again?

**Comment by haaase** [comment]
You were right, this fixed it. Seems to be an issue of markdown-preview-plus. Sorry that I did not spot the reference in the stack trace in the first place. Thanks!
