### ISSUE TITLE
Uncaught TypeError: Cannot read property 'map' of undefined

### ISSUE THREAD

**Issue by qiquanzhijia** [zhuochun/md-writer#296]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.40.1 x64
**Electron**: 3.1.10
**OS**: Microsoft Windows 10 Pro N
**Thrown From**: [markdown-writer](https://github.com/zhuochun/md-writer) package 2.11.9

### Stack Trace

Uncaught TypeError: Cannot read property 'map' of undefined

```
At C:\Users\xiaxiaozheng\.atom\packages\markdown-writer\lib\views\manage-post-tags-view.coffee:14

TypeError: Cannot read property 'map' of undefined
    at /packages/markdown-writer/lib/views/manage-post-tags-view.coffee:14:24)
    at fire (/packages/markdown-writer/node_modules/jquery/dist/jquery.js:3099:30)
    at /packages/markdown-writer/node_modules/jquery/dist/jquery.js:3211:7)
    at done (/packages/markdown-writer/node_modules/jquery/dist/jquery.js:8264:14)
    at /packages/markdown-writer/node_modules/jquery/dist/jquery.js:8605:9)
```

### Commands

```
     -1:46.5.0 markdown-writer:manage-post-tags (input.hidden-input)
     -0:21.6.0 core:cancel (input.hidden-input)
```

### Non-Core Packages

```
atom-translator 0.3.0 
git-plus 8.7.1 
hexo-insert-image 4.0.0 
language-markdown 0.37.0 
markdown-preview-enhanced 0.16.3 
markdown-scroll-sync 2.1.2 
markdown-writer 2.11.9 
tool-bar 1.1.12 
tool-bar-markdown-writer 0.5.0 
```

**Comment by qiquanzhijia** [comment]
I‘ve solved it.
