### ISSUE TITLE
Failed to activate the markdown-writer package

### ISSUE THREAD

**Issue by d2s** [zhuochun/md-writer#40]
## Steps to reproduce

1. Open Atom (with no projects open)
2. `Tree view: Add Root Folder` (for the location where Jekyll’s files are located)
3. `Markdown Writer: New Post`
4. Error dialog appears.

![screen shot 2015-04-04 at 6 18 01 pm atom tree view add root folder](https://cloud.githubusercontent.com/assets/135053/6993306/cc3828c8-daf8-11e4-93d1-4a58504269f9.png)

![screen shot 2015-04-04 at 6 20 21 pm atom markdown writer new post](https://cloud.githubusercontent.com/assets/135053/6993307/d843460c-daf8-11e4-8ba6-71af84fee39f.png)

_Error visible_
![screen shot 2015-04-04 at 6 20 47 pm atom markdown writer syntax error](https://cloud.githubusercontent.com/assets/135053/6993282/3fb69678-daf8-11e4-8ddc-1086cf57dde8.png)

## Project config file

I have basic config file for the project (based on the [example](https://github.com/zhuochun/zhuochun.github.io/commit/cb34e3c16d42c52b281c34920ad55bbca223ac23) from the md-writer documentation).

![screen shot 2015-04-04 at 6 19 51 pm atom markdown writer config](https://cloud.githubusercontent.com/assets/135053/6993262/cf014ad6-daf7-11e4-8606-f9808ec75dfe.png)

## Details from Atom

**Atom Version**: 0.189.0
**System**: Mac OS X 10.8.5
**Thrown From**: [markdown-writer](https://github.com/zhuochun/md-writer) package, v1.1.1

### Stack Trace

Failed to activate the markdown-writer package

```
At Syntax error on line 1, column 1: One top level value expected

SyntaxError: Syntax error on line 1, column 1: One top level value expected
  at nodeTransforms.Block (/Applications/Atom.app/Contents/Resources/app/node_modules/season/node_modules/cson-parser/lib/parse.js:74:15)
  at transformNode (/Applications/Atom.app/Contents/Resources/app/node_modules/season/node_modules/cson-parser/lib/parse.js:197:12)
  at Object.parse (/Applications/Atom.app/Contents/Resources/app/node_modules/season/node_modules/cson-parser/lib/parse.js:203:12)
  at parseObject (/Applications/Atom.app/Contents/Resources/app/node_modules/season/lib/cson.js:42:23)
  at parseContentsSync (/Applications/Atom.app/Contents/Resources/app/node_modules/season/lib/cson.js:67:14)
  at Object.module.exports.readFileSync (/Applications/Atom.app/Contents/Resources/app/node_modules/season/lib/cson.js:154:14)
  at Configuration._loadProjectConfig (/Users/d2s/.atom/packages/markdown-writer/lib/config.coffee:127:19)
  at Configuration.getProject (/Users/d2s/.atom/packages/markdown-writer/lib/config.coffee:121:6)
  at Configuration.getEngine (/Users/d2s/.atom/packages/markdown-writer/lib/config.coffee:105:15)
  at Configuration.getCurrentDefault (/Users/d2s/.atom/packages/markdown-writer/lib/config.coffee:111:6)
  at Object.<anonymous> (/Users/d2s/.atom/packages/markdown-writer/lib/main.coffee:38:21)
  at Object.<anonymous> (/Users/d2s/.atom/packages/markdown-writer/lib/main.coffee:1:1)
  at Module._compile (module.js:452:26)
  at Object.requireCoffeeScript (/Applications/Atom.app/Contents/Resources/app/node_modules/coffee-cash/lib/coffee-cash.js:85:19)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Package.module.exports.Package.requireMainModule (/Applications/Atom.app/Contents/Resources/app/src/package.js:678:34)
  at Package.module.exports.Package.activateConfig (/Applications/Atom.app/Contents/Resources/app/src/package.js:257:12)
  at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app/src/package.js:236:14)
  at /Applications/Atom.app/Contents/Resources/app/src/package.js:741:25
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:82:11)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:223:20)
  at /Applications/Atom.app/Contents/Resources/app/src/command-registry.js:3:61
  at CommandPaletteView.module.exports.CommandPaletteView.confirmed (/Applications/Atom.app/Contents/Resources/app/node_modules/command-palette/lib/command-palette-view.js:120:32)
  at CommandPaletteView.module.exports.SelectListView.confirmSelection (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-space-pen-views/lib/select-list-view.js:338:21)
  at space-pen-div.atom.commands.add.core:confirm (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-space-pen-views/lib/select-list-view.js:109:19)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:242:29)
  at /Applications/Atom.app/Contents/Resources/app/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:552:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:392:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:180:20)

```

### Commands

```
     -0:28.1 core:close (div.release-notes.padded.pane-item.native-key-bindings)
     -0:27.1 command-palette:toggle (atom-text-editor.editor.is-focused)
     -0:24.2 core:confirm (atom-text-editor.editor.mini)
     -0:24.2 tree-view:add-root-folder (atom-text-editor.editor.is-focused)
     -0:20.9 command-palette:toggle (atom-text-editor.editor.is-focused)
     -0:13.0 core:confirm (atom-text-editor.editor.mini)
     -0:12.5 core:save (atom-text-editor.editor.is-focused)
     -0:06.0 command-palette:toggle (atom-text-editor.editor.is-focused)
     -0:03.9 core:select-all (atom-text-editor.editor.mini)
     -0:01.7 core:confirm (atom-text-editor.editor.mini)
     -0:01.4 markdown-writer:new-post (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "linter-clojure",
      "language-csharp",
      "metrics"
    ],
    "projectHome": "/Users/d2s/Sites"
  }
}
```

### Installed Packages

```coffee
# User
angularjs, v0.2.0
atom-beautify, v0.23.1
color-picker, v1.5.0
git-log, v0.3.0
language-clojure, v0.13.0
linter, v0.12.0
linter-clang, v2.25.1
linter-erb, v0.1.0
linter-eslint, v0.5.0
linter-htmlhint, v0.0.12
linter-javac, v0.1.3
linter-jscs, v1.9.0
linter-pep8, v0.1.0
linter-php, v0.0.12
linter-ruby, v0.1.4
linter-scss-lint, v0.0.14
linter-xmllint, v0.0.5
markdown-writer, v1.1.1
minimap, v4.7.5
minimap-color-highlight, v4.1.0
minimap-find-and-replace, v4.2.0
minimap-git-diff, v4.1.2
minimap-highlight-selected, v4.2.0
minimap-selection, v4.2.0

# Dev
No dev packages
```

**Comment by zhuochun** [comment]
You need to remove the `+` sign at the beginning of all the lines. The `+` sign is diff notation. The actual format should looks like [this](https://github.com/zhuochun/zhuochun.github.io/blob/cb34e3c16d42c52b281c34920ad55bbca223ac23/_mdwriter.cson)

**Comment by d2s** [comment]
Ouch, my mistake.

Now it seems to work.
