### ISSUE TITLE
Trying to use Post search

### ISSUE THREAD

**Issue by stevencombs** [zhuochun/md-writer#44]
Received:

[Enter steps to reproduce below:]

1. ...Highlight word
2. ...⌘+⇧+K
3. …Enter a search term

**Atom Version**: 0.190.0
**System**: Mac OS X 10.10.3
**Thrown From**: [markdown-writer](https://github.com/zhuochun/md-writer) package, v1.1.1

### Stack Trace

Uncaught TypeError: undefined is not a function

```
At /Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/history.js:128

TypeError: undefined is not a function
  at /Users/stevencombs/.atom/packages/markdown-writer/lib/insert-link-view.coffee:101:42
  at Array.filter (native)
  at InsertLinkView.module.exports.InsertLinkView.updateSearch (/Users/stevencombs/.atom/packages/markdown-writer/lib/insert-link-view.coffee:100:21)
  at /Users/stevencombs/.atom/packages/markdown-writer/lib/insert-link-view.coffee:38:8
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:82:11)
  at /Applications/Atom.app/Contents/Resources/app/src/text-editor.js:220:32
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:82:11)
  at DisplayBuffer.module.exports.DisplayBuffer.emitDidChange (/Applications/Atom.app/Contents/Resources/app/src/display-buffer.js:297:20)
  at DisplayBuffer.module.exports.DisplayBuffer.handleBufferMarkersUpdated (/Applications/Atom.app/Contents/Resources/app/src/display-buffer.js:1594:21)
  at /Applications/Atom.app/Contents/Resources/app/src/display-buffer.js:5:61
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:82:11)
  at TextBuffer.module.exports.TextBuffer.applyPatch (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:557:20)
  at TextBuffer.module.exports.TextBuffer.setTextInRange (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:461:12)
  at Selection.module.exports.Selection.insertText (/Applications/Atom.app/Contents/Resources/app/src/selection.js:452:43)
  at /Applications/Atom.app/Contents/Resources/app/src/text-editor.js:718:31
  at /Applications/Atom.app/Contents/Resources/app/src/text-editor.js:760:29
  at History.module.exports.History.transact (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/history.js:119:18)
  at TextBuffer.module.exports.TextBuffer.transact (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:647:27)
  at TextEditor.module.exports.TextEditor.transact (/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:1109:26)
  at /Applications/Atom.app/Contents/Resources/app/src/text-editor.js:754:24
  at TextEditor.module.exports.TextEditor.mergeSelections (/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:1931:18)
  at TextEditor.module.exports.TextEditor.mergeIntersectingSelections (/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:1901:35)
  at TextEditor.module.exports.TextEditor.mutateSelectedText (/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:752:19)
  at TextEditor.module.exports.TextEditor.insertText (/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:715:21)
  at /Applications/Atom.app/Contents/Resources/app/src/text-editor-component.js:438:31
  at History.module.exports.History.transact (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/history.js:119:18)
  at TextBuffer.module.exports.TextBuffer.transact (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:647:27)
  at TextEditor.module.exports.TextEditor.transact (/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:1109:26)
  at TextEditorComponent.module.exports.TextEditorComponent.onTextInput (/Applications/Atom.app/Contents/Resources/app/src/text-editor-component.js:436:35)
  at HTMLDivElement.<anonymous> (/Applications/Atom.app/Contents/Resources/app/src/text-editor-component.js:3:61)

```

### Commands

```
     -8:32.1 markdown-writer:manage-post-tags (div.settings-view.pane-item)
     -7:43.5 markdown-writer:insert-new-line (atom-text-editor.editor)
  4x -7:40.4 core:select-left (atom-text-editor.editor)
     -7:37.6 markdown-writer:toggle-keystroke-text (atom-text-editor.editor)
     -7:34.9 core:undo (atom-text-editor.editor)
     -7:29.2 markdown-writer:insert-link (atom-text-editor.editor)
  9x -7:19.4 core:backspace (atom-text-editor.editor.mini)
     -6:45.6 core:confirm (atom-text-editor.editor.mini)
     -5:36.6 core:undo (atom-text-editor.editor)
     -5:34.5 markdown-writer:insert-link (atom-text-editor.editor)
     -5:30.2 core:confirm (atom-text-editor.editor.mini)
     -5:27.7 core:undo (atom-text-editor.editor)
     -5:25.8 markdown-writer:insert-link (atom-text-editor.editor)
     -5:15.8 core:cancel (atom-text-editor.editor.mini)
     -4:08.0 symbols-view:toggle-file-symbols (div.settings-view.pane-item)
     -0:15.3 markdown-writer:insert-link (atom-text-editor.editor)
```

### Config

```json
{
  "core": {},
  "markdown-writer": {
    "siteDraftsDir": "_drafts",
    "siteImagesDir": "images",
    "siteLocalDir": "/Users/stevencombs/Dropbox/stevencombs.github.io",
    "sitePostsDir": "_posts",
    "siteUrl": "http://www.stevencombs.com",
    "fileExtension": ".md",
    "siteEngine": "jekyll",
    "urlForCategories": "http://stevencombs.github.io/categories.json",
    "urlForTags": "http://stevencombs.github.io/tags.json",
    "urlForPosts": "http://stevencombs.github.io/posts.json"
  }
}
```

### Installed Packages

```coffee
# User
file-icons, v1.5.4
markdown-writer, v1.1.1

# Dev
No dev packages
```

**Comment by zhuochun** [comment]
Thanks for reporting. I will fix this ASAP.
