### ISSUE TITLE
Uncaught TypeError: Cannot read property 'join' of undefined

### ISSUE THREAD

**Issue by thellef** [zhuochun/md-writer#63]
[Enter steps to reproduce below:]

1 Select packages and Marcdown writer - Front matter
2. Select manage categories

**Atom Version**: 1.0.4
**System**: Unknown Windows Version
**Thrown From**: [markdown-writer](https://github.com/zhuochun/md-writer) package, v1.8.1

### Stack Trace

Uncaught TypeError: Cannot read property 'join' of undefined

```
At C:\Users\tel\.atom\packages\markdown-writer\lib\manage-post-categories-view.coffee:61

TypeError: Cannot read property 'join' of undefined
  at ManagePostCategoriesView.module.exports.ManagePostCategoriesView.setEditorCategories (C:\Users\tel\.atom\packages\markdown-writer\lib\manage-post-categories-view.coffee:61:41)
  at ManagePostCategoriesView.module.exports.ManagePostCategoriesView.display (C:\Users\tel\.atom\packages\markdown-writer\lib\manage-post-categories-view.coffee:40:8)
  at atom-text-editor.<anonymous> (C:\Users\tel\.atom\packages\markdown-writer\lib\main.coffee:126:19)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (C:\Users\tel\AppData\Local\atom\app-1.0.4\resources\app.asar\src\command-registry.js:241:29)
  at CommandRegistry.handleCommandEvent (C:\Users\tel\AppData\Local\atom\app-1.0.4\resources\app.asar\src\command-registry.js:3:61)
  at CommandRegistry.module.exports.CommandRegistry.dispatch (C:\Users\tel\AppData\Local\atom\app-1.0.4\resources\app.asar\src\command-registry.js:156:19)
  at EventEmitter.<anonymous> (C:\Users\tel\AppData\Local\atom\app-1.0.4\resources\app.asar\src\window-event-handler.js:70:30)
  at emitOne (events.js:77:13)
  at EventEmitter.emit (events.js:166:7)

```

### Commands

```
     -2:56.8.0 markdown-toc:toggle (atom-text-editor.editor.is-focused)
     -2:53.5.0 core:undo (atom-text-editor.editor.is-focused)
     -2:50 core:redo (atom-text-editor.editor.is-focused)
     -2:48 markdown-preview:toggle (atom-text-editor.editor.is-focused)
     -0:41.8.0 pane:split-right (atom-text-editor.editor.is-focused)
     -0:09.0 markdown-writer:manage-post-categories (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "atom-dark-syntax"
    ],
    "audioBeep": false
  }
}
```

### Installed Packages

```coffee
# User
markdown-scroll-sync, v0.4.0
markdown-toc, v0.3.0
markdown-writer, v1.8.1

# Dev
No dev packages
```

**Comment by zhuochun** [comment]
Looks like the front matter you used is not correctly parsed. Can you provide a sample of your front matter used?

**Comment by thellef** [comment]
I am not sure what you mean With front matter? Do you mean the actual text in the .md file?

**Comment by zhuochun** [comment]
Yap, i mean the file content that caused the problem.

**Comment by zhuochun** [comment]
Nvm. I found that it will break if the file does not have any front matters. :disappointed: I will fix this in the next release.

**Comment by thellef** [comment]
Thanks for quick respons!
