### ISSUE TITLE
Uncaught YAMLException: end of the stream or a document separator is expected at line 4, column 1...

### ISSUE THREAD

**Issue by liber-pater** [zhuochun/md-writer#76]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.0.12
**System**: Mac OS X 10.10.5
**Thrown From**: [markdown-writer](https://github.com/zhuochun/md-writer) package, v1.9.3

### Stack Trace

Uncaught YAMLException: end of the stream or a document separator is expected at line 4, column 10:
    **Occured: 11/21/2013 - 11/29/2013**
             ^

```
At /Users/enidmagari/.atom/packages/markdown-writer/node_modules/js-yaml/lib/js-yaml/loader.js:166

YAMLException: end of the stream or a document separator is expected at line 4, column 10:
    **Occured: 11/21/2013 - 11/29/2013**
             ^
  at generateError (/Users/enidmagari/.atom/packages/markdown-writer/node_modules/js-yaml/lib/js-yaml/loader.js:160:10)
  at throwError (/Users/enidmagari/.atom/packages/markdown-writer/node_modules/js-yaml/lib/js-yaml/loader.js:166:9)
  at readDocument (/Users/enidmagari/.atom/packages/markdown-writer/node_modules/js-yaml/lib/js-yaml/loader.js:1498:5)
  at loadDocuments (/Users/enidmagari/.atom/packages/markdown-writer/node_modules/js-yaml/lib/js-yaml/loader.js:1538:5)
  at load (/Users/enidmagari/.atom/packages/markdown-writer/node_modules/js-yaml/lib/js-yaml/loader.js:1555:19)
  at Object.safeLoad (/Users/enidmagari/.atom/packages/markdown-writer/node_modules/js-yaml/lib/js-yaml/loader.js:1573:10)
  at /Users/enidmagari/.atom/packages/markdown-writer/lib/front-matter.coffee:23:23
  at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:826:18
  at TextBuffer.module.exports.TextBuffer.scanInRange (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:864:9)
  at TextBuffer.module.exports.TextBuffer.scan (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:822:19)
  at FrontMatter.module.exports.FrontMatter._findFrontMatter (/Users/enidmagari/.atom/packages/markdown-writer/lib/front-matter.coffee:28:20)
  at new FrontMatter (/Users/enidmagari/.atom/packages/markdown-writer/lib/front-matter.coffee:22:6)
  at ManagePostTagsView.module.exports.ManageFrontMatterView.display (/Users/enidmagari/.atom/packages/markdown-writer/lib/manage-front-matter-view.coffee:30:24)
  at atom-text-editor.<anonymous> (/Users/enidmagari/.atom/packages/markdown-writer/lib/main.coffee:130:19)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:240:29)
  at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61)
  at CommandRegistry.module.exports.CommandRegistry.dispatch (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:145:19)
  at EventEmitter.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:70:30)
  at emitOne (events.js:77:13)
  at EventEmitter.emit (events.js:169:7)

```

### Commands

```
     -9:20.7.0 settings-view:install-packages-and-themes (a.inline-block)
     -9:18.3.0 core:confirm (atom-text-editor.editor.mini.is-focused)
  5x -9:08.9.0 core:move-left (atom-text-editor.editor.mini.is-focused)
     -9:02.3.0 core:confirm (atom-text-editor.editor.mini.is-focused)
  2x -6:13.6.0 markdown-preview:toggle (atom-text-editor.editor.is-focused)
     -3:37.4.0 editor:toggle-soft-wrap (atom-text-editor.editor.is-focused)
  3x -3:25.9.0 tree-view:toggle (atom-text-editor.editor.is-focused)
     -3:17.9.0 command-palette:toggle (atom-text-editor.editor.is-focused)
     -3:10.7.0 editor:consolidate-selections (atom-text-editor.editor.mini.is-focused)
     -3:10.7.0 core:cancel (atom-text-editor.editor.mini.is-focused)
     -3:01.1.0 window:toggle-dev-tools (atom-text-editor.editor.is-focused)
     -2:12.8.0 pane:show-next-item (atom-text-editor.editor.is-focused)
     -0:16.2.0 markdown-writer:insert-link (atom-text-editor.editor.is-focused)
     -0:13.2.0 core:cancel (atom-text-editor.editor.mini.is-focused)
     -0:00.9.0 markdown-writer:manage-post-tags (atom-text-editor.editor.is-focused)
```

### Config

```json
{}
```

### Installed Packages

```coffee
# User
language-scala, v1.1.3
markdown-format, v2.5.1
markdown-scroll-sync, v0.4.2
markdown-writer, v1.9.3

# Dev
No dev packages
```

**Comment by zhuochun** [comment]
Could you provide the text that caused this error if possible? thanks.
