### ISSUE TITLE
Uncaught Error: Can't save buffer with no file path

### ISSUE THREAD

**Issue by jagatsingh** [zhuochun/md-writer#80]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.0.19
**System**: Mac OS X 10.10.5
**Thrown From**: [markdown-writer](https://github.com/zhuochun/md-writer) package, v2.0.0

### Stack Trace

Uncaught Error: Can't save buffer with no file path

```
At /Users/jagatsingh/Desktop/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1010

Error: Can't save buffer with no file path
  at TextBuffer.module.exports.TextBuffer.saveAs (/Users/jagatsingh/Desktop/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1010:15)
  at TextBuffer.module.exports.TextBuffer.save (/Users/jagatsingh/Desktop/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1004:19)
  at TextEditor.module.exports.TextEditor.save (/Users/jagatsingh/Desktop/Atom.app/Contents/Resources/app.asar/src/text-editor.js:584:26)
  at PublishDraft.module.exports.PublishDraft.trigger (/Users/jagatsingh/.atom/packages/markdown-writer/lib/commands/publish-draft.coffee:17:13)
  at atom-text-editor.<anonymous> (/Users/jagatsingh/.atom/packages/markdown-writer/lib/markdown-writer.coffee:86:19)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Users/jagatsingh/Desktop/Atom.app/Contents/Resources/app.asar/src/command-registry.js:245:29)
  at CommandRegistry.handleCommandEvent (/Users/jagatsingh/Desktop/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61)
  at CommandRegistry.module.exports.CommandRegistry.dispatch (/Users/jagatsingh/Desktop/Atom.app/Contents/Resources/app.asar/src/command-registry.js:145:19)
  at EventEmitter.<anonymous> (/Users/jagatsingh/Desktop/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:70:30)
  at emitOne (events.js:77:13)
  at EventEmitter.emit (events.js:169:7)

```

### Commands

```
     -1:42.9.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:01.5.0 markdown-writer:publish-draft (atom-text-editor.editor.is-focused)
```

### Config

```json
{}
```

### Installed Packages

```coffee
# User
atom-nikola, v1.0.0
markdown-writer, v2.0.0

# Dev
No dev packages
```

**Comment by zhuochun** [comment]
You can save your edit file first then public draft. Please remember to set your blog path in settings.

Current implementation requires the draft exists in disk first. Will fix this bug in next release. Thanks.
