### ISSUE TITLE
Uncaught TypeError: utils.setTabIndex is not a function

### ISSUE THREAD

**Issue by jonleung** [zhuochun/md-writer#85]
I ran "cmd + shift + k" on the code on the below line

```
- Walk me through this code step-by-step
````

and ran into the above error

**Atom Version**: 1.0.19
**System**: Mac OS X 10.10.3
**Thrown From**: [markdown-writer](https://github.com/zhuochun/md-writer) package, v2.0.1

### Stack Trace

Uncaught TypeError: utils.setTabIndex is not a function

```
At /Users/jon/.atom/packages/markdown-writer/lib/views/insert-link-view.coffee:34

TypeError: utils.setTabIndex is not a function
  at InsertLinkView.module.exports.InsertLinkView.initialize (/Users/jon/.atom/packages/markdown-writer/lib/views/insert-link-view.coffee:34:11)
  at InsertLinkView.View (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/node_modules/space-pen/lib/space-pen.js:184:25)
  at new InsertLinkView (/Users/jon/.atom/packages/markdown-writer/lib/views/insert-link-view.coffee:13:3)
  at atom-text-editor.<anonymous> (/Users/jon/.atom/packages/markdown-writer/lib/markdown-writer.coffee:76:25)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:245:29)
  at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61)
  at CommandRegistry.module.exports.CommandRegistry.dispatch (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:145:19)
  at EventEmitter.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:70:30)
  at emitOne (events.js:77:13)
  at EventEmitter.emit (events.js:169:7)

```

### Commands

```
  4x -0:48.2.0 core:move-right (atom-text-editor.editor.vim-mode.insert-mode.is-focused)
  2x -0:46.7.0 markdown-writer:insert-new-line (atom-text-editor.editor.vim-mode.insert-mode.is-focused)
     -0:40 editor:delete-to-beginning-of-line (atom-text-editor.editor.vim-mode.insert-mode.is-focused)
  4x -0:30.1.0 core:backspace (atom-text-editor.editor.vim-mode.insert-mode.is-focused)
     -0:25.8.0 core:save (atom-text-editor.editor.vim-mode.insert-mode.is-focused)
  2x -0:24.2.0 markdown-writer:insert-new-line (atom-text-editor.editor.vim-mode.insert-mode.is-focused)
     -0:21.9.0 editor:select-to-end-of-line (atom-text-editor.editor.vim-mode.insert-mode.is-focused)
  3x -0:20.3.0 core:backspace (atom-text-editor.editor.vim-mode.insert-mode.is-focused)
     -0:15.3.0 core:save (atom-text-editor.editor.vim-mode.insert-mode.is-focused)
     -0:13.4.0 core:copy (atom-text-editor.editor.vim-mode.insert-mode.is-focused)
     -0:11.8.0 editor:select-to-end-of-line (atom-text-editor.editor.vim-mode.insert-mode.is-focused)
     -0:11.4.0 markdown-writer:insert-link (atom-text-editor.editor.vim-mode.insert-mode.is-focused)
  3x -0:08.8.0 blur (atom-text-editor.editor.vim-mode.insert-mode.is-focused)
     -0:07.8.0 markdown-writer:insert-link (atom-text-editor.editor.vim-mode.insert-mode.is-focused)
  3x -0:05.4.0 blur (atom-text-editor.editor.vim-mode.insert-mode.is-focused)
     -0:01.1.0 markdown-writer:insert-link (atom-text-editor.editor.vim-mode.insert-mode.is-focused)
```

### Config

```json
{
  "core": {
    "excludeVcsIgnoredPaths": false,
    "themes": [
      "atom-light-ui",
      "solarized-light-syntax"
    ],
    "disabledPackages": [
      "text-transformer"
    ]
  },
  "markdown-writer": {}
}
```

### Installed Packages

```coffee
# User
Sublime-Style-Column-Selection, v1.3.0
atom-text-transformer, v0.7.0
livereload, v0.3.3
markdown-table-formatter, v2.5.3
markdown-writer, v2.0.1
sequential-command, v0.3.0
soft-wrap-indicator, v0.7.0
vim-mode, v0.61.0

# Dev
No dev packages
```

**Comment by zhuochun** [comment]
Can you try restart Atom? It should be solved by a restart.

**Comment by zhuochun** [comment]
I assumed this is resolved by restart Atom. If not, feel free to reopen this issue.
