### ISSUE TITLE
Find out why package is not reloaded correctly after package updated

### ISSUE THREAD

**Issue by zhuochun** [zhuochun/md-writer#86]
Package is not correctly loaded after package updated in Atom. E.g. #84 #85 #64 #58 

Usually the problem is solved by restart Atom.

Would like to spend some time to figure out why this happens.

**Comment by zhuochun** [comment]
Happened to saw this issue from atom-elixir https://github.com/msaraiva/atom-elixir/issues/19

The issue provided some reproducible ways to test this bug.

**Comment by zhuochun** [comment]
@BinaryMuse Sorry for looping you into this issue.

I am following your steps in https://github.com/msaraiva/atom-elixir/issues/19 to test my package:

``` js
packageName = "markdown-writer"
atom.packages.deactivatePackage(packageName)
atom.packages.unloadPackage(packageName)
Object.keys(require.cache).forEach(key => delete require.cache[key])
p = atom.packages.activatePackage(packageName)
p.catch(function(err) { console.log("markdown-writer"); console.log(err); })
```

The promise stays in `pending` and the catch is never triggered. After I close and re-open devtool, I am getting this error:

```
Uncaught (in promise) TypeError: Cannot redefine property: .ts
    at Function.defineProperty (native)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:203:10
    at Array.forEach (native)
    at Object.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:200:24)
    at Module._compile (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at new Task (/Applications/Atom.app/Contents/Resources/app.asar/src/task.js:31:26)
    at Function.module.exports.Task.once (/Applications/Atom.app/Contents/Resources/app.asar/src/task.js:17:14)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/git-repository.js:398:42
    at GitRepository.module.exports.GitRepository.refreshStatus (/Applications/Atom.app/Contents/Resources/app.asar/src/git-repository.js:380:21)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/git-repository.js:81:26```

Would appreciate it if you can help. Thanks.
