### ISSUE TITLE
Uncaught Error: Cannot find module './commands' when pressing Enter key

### ISSUE THREAD

**Issue by lsdriscoll** [zhuochun/md-writer#94]
1. Open a MarkDown file
2. Place cursor anywhere in file
3. Press the Enter key

**Atom Version**: 1.2.4
**System**: Mac OS X 10.11.1
**Thrown From**: [markdown-writer](https://github.com/zhuochun/md-writer) package, v2.0.1

### Stack Trace

Uncaught Error: Cannot find module './commands'

```
At module.js:338

Error: Cannot find module './commands'
    at Module._resolveFilename (module.js:336:15)
    at Function.Module._resolveFilename (/Applications/Atom.app/Contents/Resources/app.asar/src/module-cache.js:383:52)
    at Function.Module._load (module.js:286:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at atom-text-editor.<anonymous> (/Users/lee/.atom/packages/markdown-writer/lib/main.coffee:171:31)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:533:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:356:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeydown (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:99:36)
    at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:3:61)
```

### Commands

```
     -2:04.9.0 tree-view:add-folder (span.name.icon.icon-file-directory)
     -1:49 core:confirm (atom-text-editor.editor.mini.is-focused)
     -1:38.2.0 tree-view:add-file (span.name.icon.icon-file-directory)
  4x -0:57.9.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -0:49.6.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:49.6.0 markdown-preview-plus:toggle (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-isotope-ui)
     -0:47.9.0 core:paste (atom-text-editor.editor.is-focused)
     -0:39.6.0 editor:move-to-first-character-of-line (atom-text-editor.editor.is-focused)
     -0:38.3.0 linter:set-bubble-transparent (atom-text-editor.editor.is-focused)
  2x -0:36.7.0 core:backspace (atom-text-editor.editor.is-focused)
  2x -0:33.6.0 core:move-down (atom-text-editor.editor.is-focused)
  2x -0:32.6.0 core:move-left (atom-text-editor.editor.is-focused)
  4x -0:31.9.0 linter:set-bubble-transparent (atom-text-editor.editor.is-focused)
     -0:01.5.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:00.8.0 markdown-writer:insert-new-line (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "isotope-ui",
      "one-dark-syntax"
    ],
    "disabledPackages": [
      "markdown-preview",
      "remote-edit"
    ]
  }
}
```

### Installed Packages

```coffee
# User
atom-jinja2, v0.5.0
atom-pair, v2.0.5
editorconfig, v1.2.0
isotope-ui, v2.5.1
linter, v1.2.3
markdown-preview-plus, v2.2.2
markdown-preview-plus-opener, v0.2.0
markdown-writer, v2.0.1
terminal, v0.28.0

# Dev
No dev packages
```

**Comment by zhuochun** [comment]
Hi, you just updated Markdown-Writer plugin? Can you try restart Atom?
